#!/bin/bash

# Corporate Features - Live Testing Guide
# Run this to get quick test instructions

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🧪 CORPORATE FEATURES - LIVE TESTING GUIDE                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 DEV SERVER STATUS"
echo "━━━━━━━━━━━━━━━━━━━"
if lsof -Pi :5173 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
  echo "✅ Server running on http://localhost:5173"
else
  echo "⚠️  Server NOT running on port 5173"
  echo "   Run: npm run dev"
fi
echo ""

echo "🌐 TEST URLS"
echo "━━━━━━━━━━━"
echo ""
echo "1️⃣  EMPLOYEE ADMIN"
echo "   http://localhost:5173/admin/corporate/employees"
echo "   Test: Add/Edit/Delete employees, toggle admin, filter"
echo ""
echo "2️⃣  BUDGET DASHBOARD"
echo "   http://localhost:5173/admin/corporate/budget"
echo "   Test: View budgets, percentages, charts, filtering"
echo ""
echo "3️⃣  SETTLEMENT REPORTS"
echo "   http://localhost:5173/admin/corporate/settlement"
echo "   Test: View reports, filter, export, grouping"
echo ""

echo "🛠️  BROWSER DEVTOOLS CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open DevTools (F12) and check:"
echo ""
echo "📋 Console Tab"
echo "  □ No red errors"
echo "  □ No TypeScript warnings"
echo "  □ Messages show: 'Loading...' → 'Data loaded'"
echo ""
echo "🌐 Network Tab"
echo "  □ All requests return 200 OK"
echo "  □ Supabase queries < 1 second"
echo "  □ No failed API calls"
echo ""
echo "⚡ Performance Tab"
echo "  □ Page loads in < 3 seconds"
echo "  □ Interactions smooth (60fps)"
echo "  □ No memory leaks (watch heap)"
echo ""

echo "📊 QUICK TEST SEQUENCES"
echo "━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "👤 EMPLOYEE ADMIN Test (5 min)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Load /admin/corporate/employees"
echo "2. Click 'Tilføj medarbejder'"
echo "3. Fill form: Navn, Email, Telefon, Afdeling"
echo "4. Click 'Gem' → Should see toast + new employee"
echo "5. Click edit on employee → Form pre-fills"
echo "6. Click 'Admin' toggle → Confirmation dialog"
echo "7. Click delete → 'Slet' confirmation"
echo "8. Filter by department → List filters"
echo "✓ All actions should complete instantly"
echo ""

echo "💰 BUDGET DASHBOARD Test (5 min)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Load /admin/corporate/budget"
echo "2. See department cards with:"
echo "   - Department name"
echo "   - Budget amount"
echo "   - Current spend"
echo "   - Progress bar"
echo "   - % indicator"
echo "3. Check progress bar colors:"
echo "   □ Green: < 50%"
echo "   □ Yellow: 50-80%"
echo "   □ Red: > 80%"
echo "4. See monthly trend chart"
echo "5. Filter by month → Chart updates"
echo "✓ All numbers should be consistent"
echo ""

echo "📋 SETTLEMENT REPORTS Test (5 min)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Load /admin/corporate/settlement"
echo "2. See report cards grouped by:"
echo "   - Month (newest first)"
echo "   - Company (if multiple)"
echo "3. Each card shows:"
echo "   - Company name"
echo "   - Month + year"
echo "   - Total amount"
echo "   - # of items"
echo "   - Status badge"
echo "4. Filter by status → Cards filter"
echo "5. Click card → Details modal opens"
echo "6. See invoice breakdown"
echo "✓ All grouping should be correct"
echo ""

echo "✅ VALIDATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━"
echo "□ All 3 pages load without errors"
echo "□ CRUD operations work"
echo "□ Data updates instantly"
echo "□ Charts render correctly"
echo "□ Filters work"
echo "□ No console errors"
echo "□ No network failures"
echo "□ Responsive design works"
echo "□ Calculations accurate"
echo "□ UI looks good"
echo ""

echo "📖 DETAILED DOCS"
echo "━━━━━━━━━━━━━━"
echo "See: CORPORATE_VISUAL_TESTING_CHECKLIST.md"
echo "See: CORPORATE_LIVE_TEST_REPORT.md"
echo ""

echo "🚀 NEXT STEPS"
echo "━━━━━━━━━"
echo "1. Open browser → http://localhost:5173/admin/corporate/employees"
echo "2. Login with admin credentials"
echo "3. Follow test sequences above"
echo "4. Use checklist for detailed QA"
echo "5. Report any issues with screenshots"
echo ""

echo "✨ Ready to test!"
echo ""
